---
title: "Seismic Exploration Methods"
---

## Course overview

**Course overview of EAS : Seismic Exploration Methods**

*This course contains a comprehensive review of active-source reflection seismology and its applications. The course covers aspects of seismic data acquisition, basic data processing, and advanced (wave-equation) based imaging and inversion workflows. While the field of computational reflection seismology has mostly been directed towards the exploration & production of Oil & Gas, alternative applications of this technology will be explored that will help society navigate the energy transition. This includes the use of seismic methods to monitor and manage underground operations such as geothermal and carbon storage.*

## Class meetings

| Meeting | Location | Time                   |
|---------|----------|------------------------|
| Lecture | Skiles, Room 254  | Mon & Wed 3:30 - 4:45PM |


## Teaching team 

| Name                 | Office hours   | Location   |
|----------------------|----------------|------------|
| [Felix J. Herrmann](mailto:felix.herrmann@gatech.edu) (Instructor)    | TBD            | Zoom       |
| [Abhinav Gahlot](mailto:agahlot8@gatech.edu) (TA)                        | TBD            | Zoom       |

## Access to Piazza

Students are encouraged to post their questions on [Piazza](https://gatech.instructure.com/courses/380456/external_tools/18649) on Canvas or [Piazza direct](https://piazza.com/gatech/spring2026/eas8803fh), which will be monitored by [Abhinav Gahlot](mailto:agahlot8@gatech.edu).