---
title: "Outline^[This outline is subject to change throughout the semester. We will try to keep these updates to a minimum.
]"
subtitle: "Seismic Exploration Methods - EAS 8803 - FH"
---

## General introduction {#sec-introduction}

### Basic seismic data processing

- Explanation of the seismic method
- Seismic acquisition, different gathers, basics land and marine acquisition
- Post-stack seismic-data processing flow to create a seismic image:
   - Common-midpoint sorting
   - Normal-moveout correction
   - Stack
   - Zero-offset migration
- Time-to-depth conversion
- Time or depth migration
- Drawbacks of post-stack processing
- Intro pre-stack migration and velocity analysis

### Wavefield extrapolation, pre-stack migration, and velocity analysis

- Wavefield extrapolation via Rayleigh II
- Wavefield extrapolation via the f-k domain
- \(V(z)\) migration
- Shot record migration
- Recursive extrapolation in varying media
- Pre-stack shot migration
- One-way wave-equation migration
- Reverse-time migration
- Velocity-model estimation
   - Traveltime tomography
   - migration-velocity analysis


### Filtering

- ``f-k`` filtering
- Radon filtering
   - Linear Radon
   - Multiple-removal via parabolic Radon transform
   - Parabolic versus hyperbolic Radon
- Deconvolution

***


## Seismic data acquisition {#sec-acquisition}

- Marine acquisition
- Challenges of 3D acquisition
- Wide-azimuth marine acquisition
- Coil sampling

***

## From processing to inversion {#sec-proc-to-inversion}

- General Forward problem
- Linear Forward problem
- Forward and inverse problems nonlinear and linear
- Strict inverse for invertible matrices
- When inverse does not exist
- Least-squares solution by setting gradient least-squares solution to zero
- Inverse for non-unique problems including definition of non-uniqueness
- Minimum-norm solution
- Definition of transpose and adjoint of a matrix, unitary matrices 
- SVD
- Nullspaces
- Non-null and null spaces in terms of SVD
- Pseudo/generalized inverses
- Four cases of pseudo inverse
- Over and underdermined problems noise free and noisy
- Inverse and pseudo inverses from http://en.wikipedia.org/wiki/Fundamental_theorem_of_linear_algebra
- Condition number ill and well conditioned
- truncated SVD
- Regularization
- Conditions for well-posed problems
- Least-squares and damped least-squares inversion
- Tikhonov regularization + LS solution
- Pseudo inverse and regularization
- Deconvolution as an inversion problem ('matrix inverse’)
- Forward operator for NMO and least-squares NMO
- Removing multiples by high-resolution Radon transform

*** 

## Compressive sensing {#sec-CS}

- Nyquist sampling and aliasing
- Exploiting structure is seismic data by transform-domain sparsity promotion
- Basics of Compressive Sensing
- Design principles of Compressive Sensing
- Application of Compressive Sensing to Exploration Seismology
- Jittered sampling of shots
- Simultaneous 'land’ acquisition by summing randomly weighted shots
- Simultaneous 'marine’ acquisition with time-dithered sources

***

## Linearized inversion {#sec-lin-inv}

- Introduction linearized amplitude versus offset/angle inversion
- Linearization of the reflection and transmission coefficients w.r.t. contrasts in density, compressional, and shear wavespeeds.
- Convolutional model for seismic reflectivity
- Relation between amplitudes of seismic data in the Radon domain and the linearized reflection coefficient.
- Practical workflow for linearized inversion of amplitude-versus-offset data.

***

## RTM & FWI {#sec-RTM}

- Basics of reverse-time migration (RTM) and full-waveform inversion (FWI) via the adjoint state method from physical and mathematical perspectives
- Derivation of expressions for the Jabobian and its adjoint
- Migration as the gradient of FWI
- Least-squares migration as the Gauss-Newton Hessian of FWI
- FWI with gradient descents
- FWI with Gauss-Newton
- Latest developments
